=head1 NAME

pzkcli - command line client for ZooKeeper

=head1 DESCRIPTION

An interactive command line client for ZooKeeper. Provides a shell like interface to ZooKeeper nodes.

=head1 SYNOPSIS

    pzkcli [SERVER]

=head1 SHELL COMMANDS

=head2 cat

=head2 cd

=head2 create

=head2 get

=head2 get_acl

=head2 ls

=head2 rm

=head2 set

=head2 set_acl

=head2 stat

=head2 watch


=cut

